data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?", stringsAsFactors = FALSE)
data <- subset(data, data$Date %in% c("2/2/2007", "1/2/2007"))
data <- mutate(data, datetime = as.POSIXct(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S"))
png(file="plot3.png", width=480, height=480)
plot(data$datetime, data$Sub_metering_1, xlab = "", ylab = "Energy sub metering", main = "", type="n")
lines(data$datetime, data$Sub_metering_1, type="l", col="black")
lines(data$datetime, data$Sub_metering_2, type="l", col="red")
lines(data$datetime, data$Sub_metering_3, type="l", col="blue")
par(legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=c(1,1,1)))
dev.off()