data <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
data <- subset(data, data$Date %in% c("2/2/2007", "1/2/2007"))
png(file="plot1.png", width=480, height=480)
hist(as.numeric(data$Global_active_power), col="red", xlab="Global Active Power (kilowatts)", main="Golbal Active Power")
dev.off()